"""Frozen fixture CSV bytes for the contract stub `GET /api/reports.csv`.

Source of truth: api-contract v0.2 (frozen) §3.2 worked example, §8 viewer
fixture. These are static constants, not generated by a CSV writer engine: the
real byte-generation engine (with `neutralize_formula()`) is owned by the
backend issue and is deliberately out of scope here.

Byte profile (contract v0.2 §3): plain UTF-8, **no BOM**, comma separator (rule
4), lowercase raw labels `id,title,owner,rows` (§3.1), every record terminated
by CRLF including the last (rule 3), sorted by id ascending (§5.1). No fixture
value starts with `=`/`+`/`-`/`@` and none contains `,` `"` CR or LF, so formula
neutralization (rule 5) and minimal quoting (rule 6) are byte-inert here.
"""

from __future__ import annotations

# §3.2 admin worked example: all four visible reports (ids 1,2,3,4).
CSV_ADMIN_BYTES = (
    b"id,title,owner,rows\r\n"
    b"1,Monthly usage,ops,1200\r\n"
    b"2,Error budget,sre,48\r\n"
    b"3,Payroll summary,finance,310\r\n"
    b"4,Signup funnel,growth,5200\r\n"
)

# §8 viewer fixture: header + records 1, 2, 4 (the restricted id 3 is absent).
CSV_VIEWER_BYTES = (
    b"id,title,owner,rows\r\n"
    b"1,Monthly usage,ops,1200\r\n"
    b"2,Error budget,sre,48\r\n"
    b"4,Signup funnel,growth,5200\r\n"
)
